### ISSUE TITLE
Unable to upgrade on linux because the files already exist.

### ISSUE THREAD

**Issue by andrew-field** [lpar/goup#3]
When upgrading from 1.11.4 to 1.11.5 for linux (amd64) the process failed to unpack because the files already existed and the archiver used did not want to overwrite the files.

![andrew tuisku -go-bin_001](https://user-images.githubusercontent.com/27866671/52714958-e46c7a80-2fa3-11e9-9057-9bc5fac592e1.png)

Am I missing something?

**Comment by andrew-field** [comment]
During the goup process, in the downloadAndInstall function, the unpacker retrieved and used from the archiver library is of type TarGz. This type has an underlying flag of "OverwriteExisting" used to know whether or not to overwrite files when extracting. During the execution of downloadAndInstall the unpacker is simply cast as an Unarchiver and the OverwriteExisting flag is set to false by default. When casting the unpacker to a TarGz and setting this flag to true, the files are overwritten and the process completes. The TarGz type is retrieved from the archiver library using the archiver.ByExtension function for both linux and macOS as far as I can see.

![andrew tuisku -go-bin_002](https://user-images.githubusercontent.com/27866671/52715700-c3a52480-2fa5-11e9-965c-0184aac9044d.png)

**Comment by lpar** [comment]
It should be moving `/usr/local/go` to `/usr/local/go.bak` before trying to unpack to `/usr/local/go`, so there shouldn't be files there. In general it's not safe to unpack a Go tarball into an existing Go install, because files might have been removed from the Go distribution.

**Comment by andrew-field** [comment]
Ah yes I see that now, I'll look into it.

**Comment by andrew-field** [comment]
From what I can see the check to see whether the go install exists does not fire properly. Just working on a solution.

**Comment by lpar** [comment]
Fixed it, classic confusion on my part between os.IsExist and os.IsNotExist.
